---
services:
  broker:
    image: confluentinc/cp-kafka:7.6.1
    networks:
      - mynet
    hostname: broker
    container_name: broker
    user: "root"
    ports:
      - "7802:7802"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_HEAP_OPTS: "-Xmx2g -Xms1g"  # Increase the heap size
      KAFKA_LISTENERS: 'INTERNAL://broker:29092,PLAINTEXT_HOST://localhost:9092,EXTERNAL://0.0.0.0:7802,CONTROLLER://broker:29093'
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,PLAINTEXT_HOST://localhost:9092,EXTERNAL://172.22.56.120:7802
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,PLAINTEXT_HOST:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'      
      #Security changes for implementation of SASL_PLAINTEXT Start      
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_PLAINTEXT_HOST_SASL_ENABLED_MECHANISMS: PLAIN 
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      #KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN     
      #Security changes for implementation of SASL_PLAINTEXT End      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      #KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG_RETENTION_MS: 120000
      KAFKA_LOG_RETENTION_BYTES: 50000000
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_TOOLS_LOG4J_LOGLEVEL: INFO
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'    
    volumes:
      - /home/viadmin/kafka/secrets:/etc/kafka
      - /home/viadmin/kafka/secrets/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf    
    command: ["sh", "-c", "chown -R appuser:appuser /var/lib/kafka/data && exec /etc/confluent/docker/run"]
  
  spring-boot-kafka-server:
    image: spring-boot-kafka-server
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - broker
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16